"""Daily news digest generated by the actual telegram_bot.py agent (same
Agent class, same tools, same system prompt as your interactive bot)
instead of news_digest.py's bespoke Tavily+Claude call. Delivered over
the same ntfy.sh channel as news_digest.py - reuses its
send_notification() directly, unmodified.

Cost: one full agent turn (a web_search call plus a synthesis reply) at
claude-haiku-4-5 rates - a few cents at most. Uses a fresh Agent()
instance, entirely separate from telegram_bot.py's persisted session
state and lifetime AGENT_MAX_COST_USD cap.

See ../deploy/cron-notifications.md for VPS cron setup.

Env vars:
  ANTHROPIC_API_KEY        required
  ANTHROPIC_WORKSPACE_ID   optional - see telegram_bot.py's docstring
  TAVILY_API_KEY           required - without it the agent has no
                           web_search tool and can't look up today's
                           actual news instead of guessing from stale
                           training knowledge
  NTFY_TOPIC               required - same ntfy.sh topic as news_digest.py
  NEWS_QUERY               optional, default "top world news today"
"""

import os
import sys

# telegram_bot.py lives one directory up from this scheduled/ script.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from telegram_bot import Agent  # noqa: E402 - needs the sys.path insert above

import news_digest  # noqa: E402 - reuses its send_notification() unmodified

NEWS_QUERY = os.environ.get("NEWS_QUERY") or "top world news today"


def main() -> None:
    missing = [
        name
        for name in ("ANTHROPIC_API_KEY", "TAVILY_API_KEY", "NTFY_TOPIC")
        if not os.environ.get(name)
    ]
    if missing:
        raise SystemExit(f"Missing required env var(s): {', '.join(missing)}.")

    agent = Agent()
    digest = agent.send(
        f"Search the web for {NEWS_QUERY} and summarize it into a short "
        "digest, 5-8 points max, suitable for a push notification read on "
        "a phone lock screen. Plain text only, one dash-prefixed point per "
        "line, no markdown."
    )
    print(digest)
    news_digest.send_notification("Daily News Digest", digest)


if __name__ == "__main__":
    main()
