"""Embed per-word full clips (word + reading + all 3 sentences) into
vocab_word_audio.json so the ▶ button on each card plays the complete item.

Reads:  vocab_artifacts/audio/_parts/w001.mp3 … w400.mp3
        (generated by build_vocab_audio.py — word · reading · s1 · s2 · s3 JP + EN)
Writes: vocab_artifacts/vocab_word_audio.json  { "word": "<base64 mp3>", ... }

The output replaces whatever build_vocab_word_audio.py wrote; the infographic
embeds it unchanged as window.WA, so no JS changes are needed.

Usage: build_vocab_item_audio.py [out.json]
"""

import base64
import json
import re
import sys
from pathlib import Path

ROOT  = Path(__file__).resolve().parent.parent
OUT   = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "vocab_artifacts" / "vocab_word_audio.json"
PARTS = ROOT / "vocab_artifacts" / "audio" / "_parts"

_DAY_RE     = re.compile(r"day(\d+)")
_BRACKET_RE = re.compile(r"\[[぀-ヿ゠-ヿー]+\]")


def rows(path: Path):
    cols = None
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#columns:"):
            cols = line[len("#columns:"):].split("\t")
        elif line.startswith("#") or not line.strip():
            continue
        elif cols:
            yield dict(zip(cols, line.split("\t")))


def load_words() -> list[str]:
    out = []
    for f in sorted(ROOT.glob("N3_vocab_batch*.tsv")):
        out += [r["word"] for r in rows(f)]
    return out


def main() -> None:
    words = load_words()
    if not words:
        raise SystemExit("No N3_vocab_batch*.tsv files found.")

    mapping: dict[str, str] = {}
    missing = 0

    for i, word in enumerate(words, 1):
        part = PARTS / f"w{i:03d}.mp3"
        if not part.exists() or part.stat().st_size == 0:
            print(f"  skip {i:03d}: file missing or empty")
            missing += 1
            continue
        mapping[word] = base64.b64encode(part.read_bytes()).decode("ascii")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(mapping, ensure_ascii=False), encoding="utf-8")
    print(
        f"wrote {OUT.name}: {len(mapping)} clips"
        + (f"  ({missing} missing/skipped)" if missing else "")
        + f"  ->  {OUT.stat().st_size / 1e6:.1f} MB JSON"
    )


if __name__ == "__main__":
    main()
